simplified_names = {
    # keyword : Simplified Name
    'Óleos combustíveis': 'Óleos combustíveis de petróleo',
    'Carne bovina': 'Carne bovina',
    'Farelos de soja': 'Farelos de soja e outros alimentos para animais',
    'Carnes de aves': 'Carnes de aves',
    'Produtos semi-acabados': 'Produtos semi-acabados de ferro e aço',
    'Ferro-gusa': 'Ferro-gusa e outros',
    'Ouro': 'Ouro',
    'Automóveis': 'Automóveis de passageiros',
    'Demais produtos': 'Demais produtos',
    'Trigo e centeio': 'Trigo e centeio',
    'Frutas e nozes': 'Frutas e nozes',
    'Látex': 'Látex e outras gomas',
    'farmacêuticos': 'Medicamentos e produtos farmacêuticos',
    'Válvulas e tubos': 'Válvulas e tubos',
    'organo-inorgânicos': 'Compostos organo-inorgânicos',
    'Motores e máquinas': 'Motores e máquinas não elétricos',
    'Inseticidas': 'Inseticidas e outros',
    'Equipamentos de telecomunicações': 'Equipamentos de telecomunicações',
    'Carvão, mesmo em pó, mas não aglomerado': 'Carvão',
    'Óleos brutos de petróleo': 'Óleos brutos de petróleo',
    'Outros minérios e concentrados dos metais de base': 'Outros minérios',
    'Gorduras e óleos vegetais': 'Gorduras e óleos vegetais'
}
